version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "cockroach", "sql", "--insecure", "--execute=SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/.env:/app/.env
      - ./backend/mock.json:/app/mock.json
    depends_on:
      cockroachdb:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://root@cockroachdb:26257/defaultdb?sslmode=disable
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  cockroach-data:
