version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

  backend:
    build:
      context: ./backend
    depends_on:
      - cockroachdb
    environment:
      - DATABASE_URL=postgresql://german:QyVy9ycau2mxdAwxVL-Vsw@cockroachdb:26257/defaultdb?sslmode=disable
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  cockroach-data:
